React Calculator Project: Fourth Milestone
SmithVyne/react-calculator pull request #3
Opened 2020-12-02 17:25 UTC by SmithVyne

In this milestone, I implemented the calculate and operate methods and imported the calculate method to App.js as specified [here](https://microverse.pathwright.com/library/react-redux-v11/184438/path/step/106376018/)

2020-12-02 17:53 UTC, whiz25 requested changes
## Changes Required 🙏🏿 
Your app is well structured and most requirements have been met. Well done.
However, we need to fix a few things before we can merge and proceed. Check my comments for suggestions.
- [ ] Running the app locally throws the error: `TypeError: Class constructor App cannot be invoked without 'new'`. Please look into that.
- [ ] Your README file is not descriptive enough. You have a title of `Calculator by Rails`. That doesn't make sense to me. This project is built in react. Fix that.
- [ ] Add a section for contribution for those who might want to contribute to the project.

### Martin Afani

2020-12-02 17:53 UTC, whiz25 commented on src/logic/calculate.js
> +    muteData.next = null;
- multiply `total` and `next` values by `-1` if `buttonName === +/-`. This will turn the result into negative or positive.

2020-12-02 19:17 UTC, whiz25 requested changes
## Changes required 🙏🏿 
Well done fixing the README. You forgot to address one issue.
- [ ] Multiply `total` and `next` values by -1 if `buttonName === +/-` in `calculate.js`. This will turn the result into negative or positive. Make this change before submitting for another review.
- [x] I still see this error: `TypeError: Class constructor App cannot be invoked without 'new'` in the console.

### Martin Afani

2020-12-02 23:51 UTC, SmithVyne commented
> ## Changes required 🙏🏿
> Well done fixing the README. You forgot to address one issue.
> 
> * [x]  Multiply `total` and `next` values by -1 if `buttonName === +/-` in `calculate.js`. This will turn the result into negative or positive. Make this change before submitting for another review.
> * [x]  I still see this error: `TypeError: Class constructor App cannot be invoked without 'new'` in the console.
> 
> ### Martin Afani

2020-12-03 00:06 UTC, SmithVyne commented
> > ## Changes required 🙏🏿
> > Well done fixing the README. You forgot to address one issue.
> > 
> > * [x]   Multiply `total` and `next` values by -1 if `buttonName === +/-` in `calculate.js`. This will turn the result into negative or positive. Make this change before submitting for another review.
> > * [x]   I still see this error: `TypeError: Class constructor App cannot be invoked without 'new'` in the console.
> > 
> > ### Martin Afani

Hello, I have already fixed and tested this error. I am surprised you're still seeing the error message.
Also, that operation you pointed out is already covered. It seems to me that you don't understand the code. All operations are already covered in the `operate` method. It's cleaner and concise. Please check it out.

2020-12-03 03:35 UTC, bellom commented
**We should all learn to praise in public and criticize in private.🙏, we are all a professional in Microverse right 🙂 ** 

@SmithVyne, for some reason, I think he missed that, apology! .....

> > > ## Changes required 🙏🏿
> > > Well done fixing the README. You forgot to address one issue.
> > > 
> > > * [x]    Multiply `total` and `next` values by -1 if `buttonName === +/-` in `calculate.js`. This will turn the result into negative or positive. Make this change before submitting for another review.
> > > * [x]    I still see this error: `TypeError: Class constructor App cannot be invoked without 'new'` in the console.
> > > 
> > > ### Martin Afani
> 
> Hello, I have already fixed and tested this error. I am surprised you're still seeing the error message.
> Also, that operation you pointed out is already covered. It seems to me that you don't understand the code. All operations are already covered in the `operate` method. It's cleaner and concise. Please check it out.

2020-12-03 03:37 UTC, bellom approved these changes
## Hi @SmithVyne  :clap: 

**Great work making all the necessary corrections from the previous review.**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-12-03 04:32 UTC, merged